version: "3"

services:
  php:
    build:
      context: ./docker/php
      args:
        USER_ID: "${USER_ID}"
        GROUP_ID: "${GROUP_ID}"
    volumes:
      - ./:/var/www
    environment:
      - DB_HOST=db-mysql-fra1-26683-do-user-15243687-0.c.db.ondigitalocean.com
      - DB_PORT=25060
      - DB_USER=doadmin
      - DB_PASS=AVNS_BzCR2X5VXrF0z2M14nH
      - DB_NAME=defaultdb
      - CHARSET=UTF8
    command: >
      sh -c "
      php bin/console cache:clear --env=prod &&
      php-fpm
      "

  nginx:
    build:
      context: ./docker/nginx
      args:
        USER_ID: "${USER_ID}"
        GROUP_ID: "${GROUP_ID}"
    volumes:
      - ./public:/var/www/public
    ports:
      - 80:8080
    depends_on:
      - php
